<?php
$this->title = "Відео";
$this->headTitle($this->title);
?>
<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/vendor/themes/Moderna/css/videolist.css'); ?>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-10 col-lg-offset-1" >
        <?php
        if (count($this->video)) {
            foreach ($this->video as $item) {?>
                <font size="10" face="Monotype Corsiva" color="#8B0000"> <h1 style="text-align: center"><b><?= $item['title']; ?></b></h1> </font>

                <center>
                    <iframe src="<?= $item['href']; ?>?color=8B0000&title=0&byline=0&portrait=0" width="1020" height="573" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen>

                    </iframe>
                </center>
                <?php
            }
        }
        ?>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class=" col-sm-12 row">
        <?php
        if (count($this->randomList)) {
            foreach ($this->randomList as $item) { ?>
                <a href="<?php echo $this->baseUrl() ?>/ourjob/show/id/<?= $item['id']; ?>">
                    <div class="col-lg-4 col-md-4">
                        <div class="pricing-box-alt">
                            <div class="pricing-heading">
                                <img src="<?php echo $this->baseUrl() ?>/vendor/portfolio/<?= $item['img_title']; ?>"
                                     width="100%"  />
                            </div>
                            <div class="pricing-terms" style="background-color: #961717">
                                <h6><?= $item['title']; ?></h6>
                            </div>
                        </div>
                    </div>
                </a>
                <?php
            }
        }?>
    </div>
</div>
