<?php
$this->title = "Відео";
$this->headTitle($this->title);
?>
<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/vendor/themes/Moderna/css/videolist.css'); ?>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-10 col-lg-offset-1" >
        <?php
        if (count($this->video)) {
            foreach ($this->video as $item) {?>
                <h3 style="text-align: center"><b><?= $item['title']; ?></b></h3>

                <iframe src="<?= $item['href']; ?>" width="100%" height="563" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen>

                </iframe>
                <?php
            }
        }
        ?>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class=" col-sm-12 row">
        <?php
        if (count($this->randomList)) {
            foreach ($this->randomList as $item) { ?>
                <a href="<?php echo $this->baseUrl() ?>/ourjob/show/id/<?= $item['id']; ?>">
                    <div class="col-sm-4">
                        <div class="col-sm-12 thumbnail text-center">
                            <img alt="<?= $item['title']; ?>" class="img-responsive" src=
                            "<?php echo $this->baseUrl() ?>/vendor/portfolio/<?= $item['img_title']; ?>" >

                            <div class="caption">
                                <h4><?= $item['title']; ?></h4>
                            </div>
                        </div>
                    </div>
                </a>
                <?php
            }
        }?>
    </div>
</div>
