<style>
    div.circle-avatar{
        /* make it responsive */
        max-width: 100%;
        width:100%;
        height:auto;
        display:block;
        /* div height to be the same as width*/
        padding-top:100%;

        /* make it a circle */
        border-radius:50%;

        /* Centering on image`s center*/
        background-position-y: center;
        background-position-x: center;
        background-repeat: no-repeat;

        /* it makes the clue thing, takes smaller dimension to fill div */
        background-size: cover;

        /* it is optional, for making this div centered in parent*/
        margin: 0 auto;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
    }
</style>

<link href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet">

    <section id="content">

        <div class="container">
            <div class="row">

                <div class="col-md-12 col-lg-12 col-xs-12">
                    <div class="col-md-6 col-lg-6 col-xs-12" >
                        <div class="col-md-4 col-lg-4 col-md-4 col-xs-6">
                            <div class="circle-avatar" style="background-image:url(<?php echo $this->baseUrl() ?>/vendor/portfolio/contacts/llJkgyI1M0I.jpg)"></div>
                        </div>
                        <div class="col-md-8 col-lg-8 col-xs-6">
                            <h3 style="text-align: center"><b>Тарас</b></h3></br>
                            <span class="glyphicon glyphicon-phone"></span> 000 00 00 000
                        </div>
                    </div>

                    <div class="col-md-6 col-lg-6 col-xs-12" >
                        <div class="col-md-4 col-lg-4 col-xs-6">
                            <div class="circle-avatar" style="background-image:url(<?php echo $this->baseUrl() ?>/vendor/portfolio/contacts/llJkgyI1M0I.jpg)"></div>
                        </div>
                        <div class="col-md-8 col-lg-8 col-xs-6">
                            <h3 style="text-align: center"><b>Тарас</b></h3></br>
                            <span class="glyphicon glyphicon-phone"></span> 000 00 00 000
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</br></br></br></br></br></br></br></br>

</div>
<a href="#" class="scrollup"><i class="fa fa-angle-up active"></i></a>
