
<?php echo $this->headScript()->appendFile($this->baseUrl().'/bootstrap/jquery-1.10.2.min.js');?>
<?php echo $this->headScript()->appendFile($this->baseUrl().'/bootstrap/bootstrap.min.js');?>
<?php echo $this->headScript()->appendFile($this->baseUrl().'/bootstrap/custom.js');?>
<?php echo $this->headScript()->appendFile($this->baseUrl().'/bootstrap/html5shiv.js');?>

<style>

    .carousel-caption {background:none; -ms-filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#9C000000,endColorstr=#9C000000); filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#9C000000,endColorstr=#9C000000); zoom: 1;}
    .carousel-caption { bottom: 70px; background-color: rgba(0, 0, 0, 0.8); color: #fff; margin: 0; padding: 25px 25px 25px 30px; position: absolute; right: 45px; width: 295px;}
    .flex-caption h3 {color: #fff; letter-spacing: 1px; margin-bottom: 8px; text-transform: uppercase;}
    .flex-caption p {margin: 0 0 15px;}

    .carousel-caption{
        margin-left: 40%;
        margin-right: 2%;
    }
</style>
<script>
    $('.carousel').carousel({
        interval: 2000,
        pause: 'hover',
        wrap: true
    });

</script>

<div class="container">
    <div class="row">
        <div class="col-lg-12 ">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" style="height: 100%">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                </ol>

                <!-- Wrapper for slides -->
                <div class="carousel-inner" role="listbox">
                    <div class="item active">
                        <img src="<?php echo $this->baseUrl(); ?>/vendor/themes/Moderna/img/slides/first.png" width="100%" alt="..." align="center">
                        <div class="flex-caption">
                            <h3>T-FORMAT</h3>
                            <p> – це молода команда активних людей, метою якої є зібрати найкращі здобутки відео індустрії,
                                та реалізувати їх у роботах кожного клієнта</p>
                        </div>
                    </div>
                    <div class="item">
                        <img src="<?php echo $this->baseUrl(); ?>/vendor/themes/Moderna/img/slides/camera1.png" width="100%" alt="...">
                        <div class="flex-caption">
                            <h3>Найнижчі ціни за високу якість</h3>
                            <p>Ми знімаємо у форматі Full HD, що означає розширення (1920 на 1080).
                                Такий розмір дає змогу дивитися відео на великих екранах з високою якістю</p>
                        </div>
                    </div>

                    <div class="item">
                        <img src="<?php echo $this->baseUrl(); ?>/vendor/themes/Moderna/img/slides/second.png" width="100%" alt="...">
                        <div class="flex-caption">
                            <h3>Творчий підхід</h3>
                            <p>Підбір локацій для знімального процесу. Цікаві та креативні ідеї. Легкість та невимушеність в процесі зйомок</p>
                        </div>
                    </div>
                </div>

                <!-- Controls -->
                <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                    <span class=" " aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                    <span class="glyphicon-menu-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
</div>

<?php
$auth = Zend_Auth::getInstance();
$acl = Zend_Registry::get('acl');
$role = $auth->getIdentity()->role;?>
<?php
if (count($this->paginator)) { ?>

<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <section id="projects">
                <ul id="thumbs" class="portfolio">

                    <?php foreach ($this->paginator as $item) {?>
                    <li class="col-lg-3 design" data-id="id-<?= $item['id']; ?>" data-type="web">
                        <div class="item-thumbs">
                            <a class="hover-wrap fancybox" data-fancybox-group="gallery" title="<?= $item['title']; ?>"
                                href="/vendor/portfolio/news_img/<?= $item['img_name']; ?>">
                                <span class="overlay-img"></span>
                                <span class="overlay-img-thumb font-icon-plus"></span>
                            </a>
                            <?php
                            $url = "<a href=" . $this->baseUrl() . '/index/show/id/' . $item['id'] . ">
                            детальніше</a>";
                            ?>
                            <img src="/vendor/portfolio/news_img/<?= $item['img_name']; ?>"
                                alt="<?= $item['short_desc'] . $url ?>

                            ">
                        </div>
                    </li>
                    <?php } ?>

                </ul>
            </section>
        </div>
    </div>
</div>
        <?php
        $auth = Zend_Auth::getInstance();
        $acl = Zend_Registry::get('acl');
        $role = $auth->getIdentity()->role; ?>
        <?php
}
?>

<script src="<?php echo $this->baseUrl('/'); ?>/js/jquery.js"></script>
<script src="<?php echo $this->baseUrl('/'); ?>/js/jquery.easing.1.3.js"></script>
<script src="<?php echo $this->baseUrl('/'); ?>/js/bootstrap.min.js"></script>
<script src="<?php echo $this->baseUrl('/'); ?>/js/jquery.fancybox.pack.js"></script>
<script src="<?php echo $this->baseUrl('/'); ?>/js/jquery.fancybox-media.js"></script>
<script src="<?php echo $this->baseUrl('/'); ?>/js/google-code-prettify/prettify.js"></script>
<script src="<?php echo $this->baseUrl('/'); ?>/js/portfolio/jquery.quicksand.js"></script>
<script src="<?php echo $this->baseUrl('/'); ?>/js/portfolio/setting.js"></script>
<script src="<?php echo $this->baseUrl('/'); ?>/js/jquery.flexslider.js"></script>
<script src="<?php echo $this->baseUrl('/'); ?>/js/animate.js"></script>
<script src="<?php echo $this->baseUrl('/'); ?>/js/custom.js"></script>