<body>
<div class="container">
    <div class="row">
        <a href="<?= $this->baseUrl; ?>/manageadmin"">Адмінка</a></br></br></br>

        <!-- form: -->

        <?php
            echo $this->form ;
        ?>
        <!-- :form -->
        Примітка ! Перед додаванням новго запису потрібно закинути титульні зображення в директорію
        </b>/t-format.com/www/vendor/portfolio/ </b> у полі "Фото на заголовок" потрбіно вказати лише назву файлу з розширенням (jpg, jpeg,png,bmp).</br>
        Наприклад: title.jpg
    </div>
</div>

</body>
</html>