<?php if($this->identity): ?>

<?php else: ?>
    <div class="container-fluid">
        <div class="row">
            <h2 style="text-align: center">Авторизація</h2>
            </br>
            <section>
                <div class="col-xs-6 col-xs-offset-3 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
                    <?php
                        echo $this->form;
                    ?>
                </div>
            </section>
        </div>
    </div>
</br></br></br></br></br></br></br></br>
<?php endif ?>