<?php if ($this->pageCount) { ?>
    <center>
        <nav>
            <ul class="pagination">
            <?php if (isset($this->previous)) { ?>
                <li><a href="<?= $this->url(array('page' => $this->previous)); ?>  "><span aria-hidden="true">&laquo;</span></a></li>
            <?php } else { ?>
                <li><span aria-hidden="true">&laquo;</span></li>
             <?php }
            foreach ($this->pagesInRange as $page) {
                if ($page != $this->current) { ?>
                    <li> <a href="<?= $this->url(array('page' => $page)); ?>"<span aria-hidden="true"><?= $page; ?></a></li>
                <?php } else { ?>
                    <li><span aria-hidden="true"><?= $page; ?></span></li>
                <?php }
                 }  if (isset($this->next)) { ?>
                    <li> <a href="<?= $this->url(array('page' => $this->next)); ?>"span aria-hidden="true">&raquo;</span></a></li>
                <?php } else { ?>
                 <li><span aria-hidden="true">&raquo;</span></li>
                 <?php } ?>
            </ul>
        </nav>
    </center>
<?php } ?>