<?php
$this->title = "Адмінка";
$this->headTitle($this->title);
?>
<div class="container">
    <div class="row">
        <div class="col-lg-12 ">
            <a href="<?php echo $this->baseUrl() ?>/managenews">
                <div class="col-lg-4 col-md-4">
                    Блок НОВИН
                </div>
            </a>
            <a href="<?php echo $this->baseUrl() ?>/managevideos">
                <div class="col-lg-4 col-md-4">
                    Блок ВІДЕО
                </div>
            </a>
            <a href="<?php echo $this->baseUrl() ?>/manageourjob">
                <div class="col-lg-4 col-md-4">
                    Блок НАШІ РОБОТИ
                </div>
            </a>
        </div>
    </div>
</div>
</br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br>