<?php
$this->title = "Відео";
$this->headTitle($this->title);
?>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-10 col-lg-offset-1" >
        <?php
        $auth = Zend_Auth::getInstance();
        $acl = Zend_Registry::get('acl');
        $role = $auth->getIdentity()->role;

        if (count($this->paginator)) { ?>
            <?php foreach ($this->paginator as $item) {?>
                <h3 style="text-align: center"><b><?= $item['title']; ?></b></h3>

                <iframe src="<?= $item['href']; ?>" width="100%" height="563" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen>

                </iframe>
                <?php
            }
        }
        ?>
        </div>
    </div>
</div>
