<?php if ($this->pageCount) { ?>
    <div class="pagination pagination-lg">
        <?php if (isset($this->previous)) { ?>
            <a href="<?= $this->url(array('page' => $this->previous)); ?>"><</a>
        <?php } else { ?>
            <li class="disabled"><</li>
        <?php }
        foreach ($this->pagesInRange as $page) {
            if ($page != $this->current) { ?>
                <a href="<?= $this->url(array('page' => $page)); ?>"><?= $page; ?></a>
            <?php } else { ?>
                <?= $page; ?>
            <?php }
        }  if (isset($this->next)) { ?>
            <a href="<?= $this->url(array('page' => $this->next)); ?>">
                >
            </a>
        <?php } else { ?>
            <li class="disabled">></li>
        <?php } ?>
    </div>
<?php } ?>